# =========================================================================
# TOP LAYER ROUTER
# =========================================================================

#' Enrich Missing Abstracts from External Metadata APIs
#'
#' @param df A data frame generated by `fetch_all_zotero_data`.
#' @param email_contact Character. Valid email address for polite API pools.
#'   Defaults to the environment variable `POLITE_EMAIL`.
#' @param providers Named list of provider fetcher functions executed in list order.
#'   Defaults to Europe PMC -> OpenAlex -> Crossref.
#'
#' @return Data frame with updated `Abstract` column where matches were found.
#'
#' @examples
#' \dontrun{
#' # Default usage (Europe PMC -> OpenAlex -> Crossref)
#' df_enriched <- enrich_missing_abstracts(df = my_zotero_df)
#'
#' # Custom provider order: OpenAlex primary, Europe PMC secondary
#' custom_order <- list(
#'   openalex = fetch_abstract_openalex,
#'   epmc     = fetch_abstract_epmc
#' )
#'
#' df_enriched <- enrich_missing_abstracts(
#'   df = my_zotero_df,
#'   providers = custom_order
#' )
#' }
#'
#' @import httr2
#' @export
enrich_missing_abstracts <- function(df,
                                     email_contact = Sys.getenv("POLITE_EMAIL"),
                                     providers = list(
                                       epmc = fetch_abstract_epmc,
                                       crossref = fetch_abstract_crossref,
                                       openalex = fetch_abstract_openalex

                                     )) {

  if (email_contact == "") {
    warning("No valid email provided for polite API pool. Requests may be throttled.")
    email_contact <- "anonymous@example.com"
  }

  cat("Starting abstract enrichment process...\n")
  base_req <- build_base_req(email_contact)

  for (i in seq_len(nrow(df))) {
    if (is.na(df$Abstract[i]) || trimws(df$Abstract[i]) == "") {

      raw_doi <- trimws(df$DOI[i])
      raw_doi <- sub("^https?://(dx\\.)?doi\\.org/", "", raw_doi)

      if (!grepl("^10\\.", raw_doi)) next

      message(paste("Row", i, "- Attempting to fetch abstract for DOI:", raw_doi))

      # Iterate through the list of provider functions dynamically
      for (provider_name in names(providers)) {
        fetcher_fn <- providers[[provider_name]]

        abstract <- fetcher_fn(raw_doi, base_req)

        if (!is.null(abstract)) {
          df$Abstract[i] <- abstract
          message(paste0("  -> Success! Abstract retrieved from ", provider_name, "."))
          break # Exit provider loop early once found
        }
      }

      if (is.na(df$Abstract[i]) || trimws(df$Abstract[i]) == "") {
        message("  -> Could not locate abstract in configured repositories.")
      }

      Sys.sleep(0.1)
    }
  }

  return(df)
}
