#' Fetch Citation Counts from OpenAlex via Batch Queries
#'
#' @description
#' Scans a data frame for a DOI column, extracts all valid identifiers, and
#' queries the OpenAlex API in batches of up to 50 items to retrieve up-to-date
#' citation metrics (\code{cited_by_count}). The results are joined back to the
#' original data frame under a new \code{citations} column.
#'
#' @param df A data frame containing bibliographic data, typically generated by
#'   \code{fetch_all_zotero_data()}.
#' @param email_contact Character string containing the contact email used to gain entry
#'   to the OpenAlex "Polite Pool." Defaults to the system environment variable
#'   \code{Sys.getenv("POLITE_EMAIL")}.
#'
#' @return A data frame identical to the input, but with an added integer column
#'   named \code{citations} containing the citation metrics. Rows with missing or
#'   unmatched DOIs will default to \code{NA}.
#' @export
#'
#' @importFrom httr GET content user_agent
#' @importFrom dplyr mutate left_join
#'
#' @examples
#' \dontrun{
#' enriched_data <- fetch_citation_counts(raw_data)
#' }
fetch_citation_counts <- function(df, email_contact = Sys.getenv("POLITE_EMAIL")) {
  if (!is.data.frame(df)) {
    stop("Input must be a data frame.")
  }

  if (is.null(email_contact) || email_contact == "") {
    warning("No valid email provided for the polite API pool. Requests may be throttled.")
    email_contact <- "anonymous@example.com"
  } else {
    message("Email set to ", email_contact)
  }

  message("Starting citation metrics enrichment process...")

  col_names <- names(df)
  doi_idx <- which(tolower(col_names) == "doi")

  if (length(doi_idx) == 0) {
    warning("No DOI column found. Returning original data frame unchanged.")
    df$citations <- NA_integer_
    return(df)
  }

  target_doi_col <- col_names[doi_idx[1]]
  raw_dois <- df[[target_doi_col]]
  clean_dois <- unique(raw_dois[!is.na(raw_dois) & raw_dois != "" & raw_dois != "NA"])

  if (length(clean_dois) == 0) {
    df$citations <- NA_integer_
    return(df)
  }

  openalex_dois <- ifelse(
    grepl("^http", clean_dois, ignore.case = TRUE),
    clean_dois,
    paste0("https://doi.org/", clean_dois)
  )

  results_list <- list()
  chunk_size <- 50
  doi_chunks <- split(openalex_dois, ceiling(seq_along(openalex_dois) / chunk_size))

  for (i in seq_along(doi_chunks)) {
    chunk <- doi_chunks[[i]]
    doi_filter_string <- paste(chunk, collapse = "|")

    # Execute natively using classic httr::GET
    tryCatch({
      resp <- httr::GET(
        url = "https://api.openalex.org/works",
        query = list(
          filter = paste0("doi:", doi_filter_string),
          per_page = chunk_size,
          mailto = email_contact
        ),
        # Good practice: add a identifiable user agent string
        httr::user_agent("biblioview_R_package_dashboard")
      )

      # Safely parse the JSON payload content lists
      body <- httr::content(resp, as = "parsed", type = "application/json")

      if (!is.null(body$results)) {
        chunk_results <- lapply(body$results, function(work) {
          # OpenAlex always stores DOIs as absolute URLs; strip down to match raw keys
          extracted_doi <- gsub("^https://doi.org/", "", work$doi, ignore.case = TRUE)
          data.frame(
            join_doi = c(extracted_doi, work$doi),
            citations = as.integer(work$cited_by_count),
            stringsAsFactors = FALSE
          )
        })
        results_list[[length(results_list) + 1]] <- do.call(rbind, chunk_results)
      }
    }, error = function(e) {
      warning(paste("OpenAlex batch API query failed for chunk", i, ":", e$message))
    })

    Sys.sleep(0.1)
  }

  if (length(results_list) > 0) {
    lookup_table <- unique(do.call(rbind, results_list))
    lookup_table <- lookup_table[!is.na(lookup_table$join_doi), ]

    df$.temp_join_id <- df[[target_doi_col]]
    df <- dplyr::left_join(df, lookup_table, by = c(".temp_join_id" = "join_doi"))
    df$.temp_join_id <- NULL
  } else {
    df$citations <- NA_integer_
    #df$citations <- -1 # more robust
  }

  # -1 means no citation count found
  df$citations <- ifelse(is.na(df$citations), -1, df$citations)

  return(df)
}
