#' Format DOI and URL Columns into Clickable HTML Anchors
#'
#' @description
#' Scans a data frame for columns matching "doi" or "url" (case-insensitive) 
#' and transforms their string values into active HTML anchor tags (\code{<a href="...">}). 
#' It automatically protects existing full URLs inside the DOI column from being 
#' duplicated with the DOI resolver prefix.
#'
#' @param df A data frame containing bibliographic data, typically generated by 
#'   \code{fetch_all_zotero_data()}.
#'
#' @return A data frame with the matched identifier columns transformed into 
#'   HTML link strings.
#' @export
#'
#' @importFrom dplyr mutate
#'
#' @examples
#' \dontrun{
#' # Assuming raw_data contains columns named 'DOI' and 'url'
#' clean_df <- format_hyperlinks(raw_data)
#' }
format_hyperlinks <- function(df) {
  if (!is.data.frame(df)) {
    stop("Input must be a data frame.")
  }
  
  col_names <- names(df)
  
  # 1. Match and format the DOI column safely (case-insensitive)
  doi_idx <- which(tolower(col_names) == "doi")
  if (length(doi_idx) > 0) {
    target_col <- col_names[doi_idx[1]]
    df[[target_col]] <- ifelse(
      !is.na(df[[target_col]]) & df[[target_col]] != "", 
      ifelse(
        # If it already looks like a full URL link, don't prefix it again!
        grepl("^http", df[[target_col]], ignore.case = TRUE),
        paste0('<a href="', df[[target_col]], '" target="_blank">', df[[target_col]], '</a>'),
        paste0('<a href="https://doi.org/', df[[target_col]], '" target="_blank">', df[[target_col]], '</a>')
      ), 
      df[[target_col]]
    )
  }
  
  # 2. Match and format the regular Web URL column (case-insensitive)
  url_idx <- which(tolower(col_names) == "url")
  if (length(url_idx) > 0) {
    target_col <- col_names[url_idx[1]]
    df[[target_col]] <- ifelse(
      !is.na(df[[target_col]]) & df[[target_col]] != "", 
      paste0('<a href="', df[[target_col]], '" target="_blank">Link</a>'), 
      df[[target_col]]
    )
  }
  
  return(df)
}
